/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sistemapedidos.ui;

import br.com.sistemapedidos.dominio.modelos.Cliente;
import br.com.sistemapedidos.dominio.modelos.ItemDoPedido;
import br.com.sistemapedidos.dominio.modelos.Pedido;
import br.com.sistemapedidos.dominio.modelos.Produto;
import br.com.sistemapedidos.dominio.servicos.ClienteService;
import br.com.sistemapedidos.dominio.servicos.PedidoService;
import br.com.sistemapedidos.dominio.servicos.ProdutoService;
import br.com.sistemapedidos.ui.modelostabela.ModeloTabelaProduto;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author raphael
 */
public class CriarPedido extends javax.swing.JFrame {
    private List<ItemDoPedido> itens = new ArrayList<>();
    private ModeloTabelaProduto modeloTabela = new ModeloTabelaProduto();
    private ModeloTabelaProduto modeloItens = new ModeloTabelaProduto();
    private int linhaClicadaProduto = -1;
    private int linhaClicadaItem = -1;
    
    /**
     * Creates new form CriarPedido
     */
    public CriarPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaItens = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        spinnerQuantidade = new javax.swing.JSpinner();
        btnAddProduto = new javax.swing.JButton();
        btnRemoverProduto = new javax.swing.JButton();
        txtCpf = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        btnCriarPedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tabelaProdutos.setModel(modeloTabela);
        tabelaProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaProdutos);

        tabelaItens.setModel(modeloItens);
        tabelaItens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaItensMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaItens);

        jLabel1.setText("Quantidade:");

        spinnerQuantidade.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        btnAddProduto.setText("Adicionar produto");
        btnAddProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddProdutoMouseClicked(evt);
            }
        });

        btnRemoverProduto.setText("Remover produto");
        btnRemoverProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemoverProdutoMouseClicked(evt);
            }
        });

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel2.setText("CPF do Cliente:");

        btnCriarPedido.setText("Criar pedido");
        btnCriarPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCriarPedidoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnAddProduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(spinnerQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnRemoverProduto)))
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnCriarPedido))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(spinnerQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRemoverProduto)))
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCriarPedido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ProdutoService produtoService = new ProdutoService();
        List<Produto> produtos = produtoService.obterTodos();
        modeloTabela.setListaProdutos(produtos);
    }//GEN-LAST:event_formWindowOpened

    private void btnAddProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddProdutoMouseClicked
        Produto produto = modeloTabela.getProduto(linhaClicadaProduto);
        modeloItens.adicionaProduto(produto);
        modeloTabela.removeProduto(produto);
        ItemDoPedido item = new ItemDoPedido();
        item.setProduto(produto);
        item.setQuantidade((int) spinnerQuantidade.getValue());
        itens.add(item);
        spinnerQuantidade.setValue(1);
    }//GEN-LAST:event_btnAddProdutoMouseClicked

    private void tabelaProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProdutosMouseClicked
        linhaClicadaProduto = tabelaProdutos.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_tabelaProdutosMouseClicked

    private void tabelaItensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaItensMouseClicked
        linhaClicadaItem = tabelaItens.rowAtPoint(evt.getPoint());
        Produto produto = modeloItens.getProduto(linhaClicadaItem);
        ItemDoPedido itemDoPedido = itens.stream()
            .filter(item -> item.getProduto().equals(produto))
            .findFirst()
            .orElse(null);
        spinnerQuantidade.setValue(itemDoPedido.getQuantidade());
    }//GEN-LAST:event_tabelaItensMouseClicked

    private void btnRemoverProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoverProdutoMouseClicked
        Produto produto = modeloItens.getProduto(linhaClicadaItem);
        modeloTabela.adicionaProduto(produto);
        modeloItens.removeProduto(produto);
        ItemDoPedido itemDoPedido = itens.stream()
            .filter(item -> item.getProduto().equals(produto))
            .findFirst()
            .orElse(null);
        itens.remove(itemDoPedido);
        spinnerQuantidade.setValue(1);
    }//GEN-LAST:event_btnRemoverProdutoMouseClicked

    private void btnCriarPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCriarPedidoMouseClicked
        Pedido pedido = new Pedido();
        try {
            pedido.setData((Date)Calendar.getInstance().getTime());
            pedido.setItens(itens);
            ClienteService clienteService = new ClienteService();        
            Cliente cliente = clienteService.obterPorCpf(txtCpf.getText());
            pedido.setCliente(cliente);
            PedidoService pedidoService = new PedidoService();
            pedidoService.criarPedido(pedido);
            
            spinnerQuantidade.setValue(1);
            itens.forEach((item) -> {
                modeloTabela.adicionaProduto(item.getProduto());
                modeloItens.removeProduto(item.getProduto());
            });
            txtCpf.setText("");
            itens.clear();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCriarPedidoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduto;
    private javax.swing.JButton btnCriarPedido;
    private javax.swing.JButton btnRemoverProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner spinnerQuantidade;
    private javax.swing.JTable tabelaItens;
    private javax.swing.JTable tabelaProdutos;
    private javax.swing.JFormattedTextField txtCpf;
    // End of variables declaration//GEN-END:variables
}
